nome:Gerar dados

em:
  horário:#executar a cada 12 horas
    - cron: "* */12 * * *"
  workflow_dispatch:

empregos:
  construir:
    nome:Empregos para atualizar dados
    runs-on: ubuntu-latest
    passos:
      # Animação cobra
      - usa:Platane/snk@master
        id: snake-gif
        com:
          github_user_name:  cfrb22
          svg_out_path: dist/github-contribution-grid-snake.svg

      - usa:crazy-max/ghaction-github-pages@v2.1.3
        com:
          target_branch:saída
          build_dir: dist
        env:
          GITHUB_TOKEN:${{{ segredos. GITHUB_TOKEN }}
